function [tcHndl] = plotParamsVsContrast(rParams,MaxContrastLMS,rgbMatrixForPlotting)


vecContrast = sqrt(MaxContrastLMS(:,1).^2+MaxContrastLMS(:,3).^2);


tcHndl = figure;
hold on;
sz = 12;

plot(vecContrast(1:6),flipud(lags(:,1)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(1,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(1,:),...
    'Color',rgbMatrixForPlotting(1,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(7:12),flipud(lags(:,2)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(2,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(2,:),...
    'Color',rgbMatrixForPlotting(2,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(13:18),flipud(lags(:,6)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(3,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(3,:),...
    'Color',rgbMatrixForPlotting(3,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(19:24),flipud(lags(:,5)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(4,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(4,:),...
    'Color',rgbMatrixForPlotting(4,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(25:30),flipud(lags(:,4)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(5,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(5,:),...
    'Color',rgbMatrixForPlotting(5,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(31:36),flipud(lags(:,3)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(6,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(6,:),...
    'Color',rgbMatrixForPlotting(6,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

axis square;

set(gca,'Xscale','log');
set(gca,'XTick',[0.03 0.1 0.3 1]);
legend('0°','90°','-75°','75°','-45°','45°');


ylim([0.2 .6])



set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'FontSize'    , 16        , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , .2:.1:.6 , ...
  'LineWidth'   , 2         , ...
  'ActivePositionProperty', 'OuterPosition');

set(gcf, 'Color', 'white' );

hTitle  = title ('Lag Vs. Contrast');
hXLabel = xlabel('Contrast (%)'  );
hYLabel = ylabel('Lag (s)');

set([hTitle, hXLabel, hYLabel],'FontName', 'Helvetica');
set([hXLabel, hYLabel,],'FontSize', 18);
set( hTitle, 'FontSize', 18,'FontWeight' , 'bold');



