%% LOAD DATA

Sall = loadPSYdataLMSall('TRK', 'BMC', 'CGB', {[1:20]}, 'jburge-hubel', 'local');

%% SORT TRIALS BY COLOR ANGLE

% 0 DEG IN SL PLANE
ind1 = abs(atand(Sall.MaxContrastLMS(:,3)./Sall.MaxContrastLMS(:,1))-0)<0.001;
% 90 DEG IN SL PLANE
ind2 = abs(atand(Sall.MaxContrastLMS(:,3)./Sall.MaxContrastLMS(:,1))-90)<0.001;
% -45 DEG IN SL PLANE
ind3 = abs(atand(Sall.MaxContrastLMS(:,3)./Sall.MaxContrastLMS(:,1))-(-45))<0.001;
% 45 DEG IN SL PLANE
ind4 = abs(atand(Sall.MaxContrastLMS(:,3)./Sall.MaxContrastLMS(:,1))-(+45))<0.001;
% -75 DEG IN SL PLANE
ind5 = abs(atand(Sall.MaxContrastLMS(:,3)./Sall.MaxContrastLMS(:,1))-(-75))<0.001;
% 75 DEG IN SL PLANE
ind6 = abs(atand(Sall.MaxContrastLMS(:,3)./Sall.MaxContrastLMS(:,1))-(+75))<0.001;
S1 = structElementSelect(Sall,ind1,size(Sall.tgtXmm,2));
S2 = structElementSelect(Sall,ind2,size(Sall.tgtXmm,2));
S3 = structElementSelect(Sall,ind3,size(Sall.tgtXmm,2));
S4 = structElementSelect(Sall,ind4,size(Sall.tgtXmm,2));
S5 = structElementSelect(Sall,ind5,size(Sall.tgtXmm,2));
S6 = structElementSelect(Sall,ind6,size(Sall.tgtXmm,2));

%% LMS ANALYSIS TO ESTIMATE LAGS

[~,~,rParams(:,:,1)] = LMSxcorrAnalysis(S1,'LGS');
close all
[~,~,rParams(:,:,2)] = LMSxcorrAnalysis(S2,'LGS');
close all
[~,~,rParams(:,:,3)] = LMSxcorrAnalysis(S3,'LGS');
close all
[~,~,rParams(:,:,4)] = LMSxcorrAnalysis(S4,'LGS');
close all
[~,~,rParams(:,:,5)] = LMSxcorrAnalysis(S5,'LGS');
close all
[~,~,rParams(:,:,6)] = LMSxcorrAnalysis(S6,'LGS');
close all

%% PLOT ALL LAGS ON SAME FIGURE

lags = squeeze(rParams(2,:,:));
MaxContrastLMS = LMSstimulusContrast('experiment','SLplane-Pos');

rgbMatrixForPlotting = [230 172 178; ...
    194  171  253; ...
    253  182    44; ...
    252  153  233;...
    36   210  201; ...
    32   140  163 ...
    ]./255;

vecContrast = sqrt(MaxContrastLMS(:,1).^2+MaxContrastLMS(:,3).^2);


tcHndl = figure;
hold on;
sz = 12;

plot(vecContrast(1:6),flipud(lags(:,1)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(1,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(1,:),...
    'Color',rgbMatrixForPlotting(1,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(7:12),flipud(lags(:,2)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(2,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(2,:),...
    'Color',rgbMatrixForPlotting(2,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(13:18),flipud(lags(:,6)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(3,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(3,:),...
    'Color',rgbMatrixForPlotting(3,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(19:24),flipud(lags(:,5)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(4,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(4,:),...
    'Color',rgbMatrixForPlotting(4,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(25:30),flipud(lags(:,4)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(5,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(5,:),...
    'Color',rgbMatrixForPlotting(5,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(31:36),flipud(lags(:,3)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(6,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(6,:),...
    'Color',rgbMatrixForPlotting(6,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

axis square;

set(gca,'Xscale','log');
set(gca,'XTick',[0.03 0.1 0.3 1]);
legend('0°','90°','-75°','75°','-45°','45°');


ylim([0.2 .6])



set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'FontSize'    , 16        , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , .2:.1:.6 , ...
    'LineWidth'   , 2         , ...
    'ActivePositionProperty', 'OuterPosition');

set(gcf, 'Color', 'white' );

hTitle  = title ('Lag Vs. Contrast');
hXLabel = xlabel('Contrast (%)'  );
hYLabel = ylabel('Lag (s)');

set([hTitle, hXLabel, hYLabel],'FontName', 'Helvetica');
set([hXLabel, hYLabel,],'FontSize', 18);
set( hTitle, 'FontSize', 18,'FontWeight' , 'bold');


figSavePath = '/Users/michael/labDropbox/CNST_analysis/ColorTracking/Results/';
subjID = 'Subject2';
set(tcHndl, 'Renderer', 'Painters');
figureSizeInches = [8 8];
set(tcHndl, 'PaperUnits', 'inches');
set(tcHndl, 'PaperSize',figureSizeInches);
set(tcHndl, 'PaperPosition', [0 0 figureSizeInches(1) figureSizeInches(2)]);
% Full file name
figNameTc =  fullfile(figSavePath,[subjID, '_LagVsContrast.pdf']);
% Save it
print(tcHndl, figNameTc, '-dpdf', '-r300');

%% Plot integration time
stds = squeeze(rParams(3,:,:));

tips = exp(log(lags)+stds.*sqrt(log(4))) - exp(log(lags)-stds.*sqrt(log(4)));

MaxContrastLMS = LMSstimulusContrast('experiment','SLplane-Pos');

rgbMatrixForPlotting = [230 172 178; ...
    194  171  253; ...
    253  182    44; ...
    252  153  233;...
    36   210  201; ...
    32   140  163 ...
    ]./255;

vecContrast = sqrt(MaxContrastLMS(:,1).^2+MaxContrastLMS(:,3).^2);


tcHndl = figure;
hold on;
sz = 12;

plot(vecContrast(1:6),flipud(tips(:,1)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(1,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(1,:),...
    'Color',rgbMatrixForPlotting(1,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(7:12),flipud(tips(:,2)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(2,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(2,:),...
    'Color',rgbMatrixForPlotting(2,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(13:18),flipud(tips(:,6)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(3,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(3,:),...
    'Color',rgbMatrixForPlotting(3,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(19:24),flipud(tips(:,5)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(4,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(4,:),...
    'Color',rgbMatrixForPlotting(4,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(25:30),flipud(tips(:,4)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(5,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(5,:),...
    'Color',rgbMatrixForPlotting(5,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(31:36),flipud(tips(:,3)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(6,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(6,:),...
    'Color',rgbMatrixForPlotting(6,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

axis square;

set(gca,'Xscale','log');
set(gca,'XTick',[0.03 0.1 0.3 1]);
legend('0°','90°','-75°','75°','-45°','45°');


ylim([0.1 0.4])



set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'FontSize'    , 16        , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , 0.1:.1:.4 , ...
    'LineWidth'   , 2         , ...
    'ActivePositionProperty', 'OuterPosition');

set(gcf, 'Color', 'white' );

hTitle  = title ('TIP Vs. Contrast');
hXLabel = xlabel('Contrast (%)'  );
hYLabel = ylabel('Integration Period (s)');

set([hTitle, hXLabel, hYLabel],'FontName', 'Helvetica');
set([hXLabel, hYLabel,],'FontSize', 18);
set( hTitle, 'FontSize', 18,'FontWeight' , 'bold');


figSavePath = '/Users/michael/labDropbox/CNST_analysis/ColorTracking/Results/';
subjID = 'Subject2';
set(tcHndl, 'Renderer', 'Painters');
figureSizeInches = [8 8];
set(tcHndl, 'PaperUnits', 'inches');
set(tcHndl, 'PaperSize',figureSizeInches);
set(tcHndl, 'PaperPosition', [0 0 figureSizeInches(1) figureSizeInches(2)]);
% Full file name
figNameTc =  fullfile(figSavePath,[subjID, '_TipVsContrast.pdf']);
% Save it
print(tcHndl, figNameTc, '-dpdf', '-r300');

%% plot the amp
%% Plot integration time
amps = squeeze(rParams(1,:,:));

MaxContrastLMS = LMSstimulusContrast('experiment','SLplane-Pos');

rgbMatrixForPlotting = [230 172 178; ...
    194  171  253; ...
    253  182    44; ...
    252  153  233;...
    36   210  201; ...
    32   140  163 ...
    ]./255;

vecContrast = sqrt(MaxContrastLMS(:,1).^2+MaxContrastLMS(:,3).^2);


tcHndl = figure;
hold on;
sz = 12;

plot(vecContrast(1:6),flipud(amps(:,1)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(1,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(1,:),...
    'Color',rgbMatrixForPlotting(1,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(7:12),flipud(amps(:,2)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(2,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(2,:),...
    'Color',rgbMatrixForPlotting(2,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(13:18),flipud(amps(:,6)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(3,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(3,:),...
    'Color',rgbMatrixForPlotting(3,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(19:24),flipud(amps(:,5)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(4,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(4,:),...
    'Color',rgbMatrixForPlotting(4,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(25:30),flipud(amps(:,4)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(5,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(5,:),...
    'Color',rgbMatrixForPlotting(5,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

plot(vecContrast(31:36),flipud(amps(:,3)),'o--', ...
    'MarkerEdgeColor',.3*rgbMatrixForPlotting(6,:),...
    'MarkerFaceColor',rgbMatrixForPlotting(6,:),...
    'Color',rgbMatrixForPlotting(6,:),...
    'LineWidth',2,...
    'MarkerSize',sz);

axis square;

set(gca,'Xscale','log');
set(gca,'XTick',[0.03 0.1 0.3 1]);
legend('0°','90°','-75°','75°','-45°','45°');


ylim([0 0.2])



set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'FontSize'    , 16        , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , 0:.05:.2 , ...
    'LineWidth'   , 2         , ...
    'ActivePositionProperty', 'OuterPosition');

set(gcf, 'Color', 'white' );

hTitle  = title ('Amplitude Vs. Contrast');
hXLabel = xlabel('Contrast (%)'  );
hYLabel = ylabel('Amplitude (a.u.)');

set([hTitle, hXLabel, hYLabel],'FontName', 'Helvetica');
set([hXLabel, hYLabel,],'FontSize', 18);
set( hTitle, 'FontSize', 18,'FontWeight' , 'bold');


figSavePath = '/Users/michael/labDropbox/CNST_analysis/ColorTracking/Results/';
subjID = 'Subject2';
set(tcHndl, 'Renderer', 'Painters');
figureSizeInches = [8 8];
set(tcHndl, 'PaperUnits', 'inches');
set(tcHndl, 'PaperSize',figureSizeInches);
set(tcHndl, 'PaperPosition', [0 0 figureSizeInches(1) figureSizeInches(2)]);
% Full file name
figNameTc =  fullfile(figSavePath,[subjID, '_AmpVsContrast.pdf']);
% Save it
print(tcHndl, figNameTc, '-dpdf', '-r300');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%          S/L+S
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
lags = squeeze(rParams(2,:,:));
MaxContrastLMS = LMSstimulusContrast('experiment','SLplane-Pos');
S_over_LS =  MaxContrastLMS(:,3) ./ (abs(MaxContrastLMS(:,1))+abs(MaxContrastLMS(:,3)));
rgbMatrixForPlotting = [230 172 178; ...
    194  171  253; ...
    253  182    44; ...
    252  153  233;...
    36   210  201; ...
    32   140  163 ...
    ]./255;

vecContrast = sqrt(MaxContrastLMS(:,1).^2+MaxContrastLMS(:,3).^2);

matContrast = reshape(vecContrast,size(lags));

scaledContrast = matContrast./matContrast(1,:);

tcHndl = figure;
hold on;
sz = 12.^2;

for ii = 1:size(lags,1)
    scatter(S_over_LS(ii),flipud(lags(ii,1)),sz, ...
        'MarkerEdgeColor',.3*rgbMatrixForPlotting(1,:),...
        'MarkerFaceColor',rgbMatrixForPlotting(1,:),...
        'MarkerFaceAlpha', scaledContrast(ii,1));
    
    scatter(S_over_LS(ii+6),flipud(lags(ii,2)),sz, ...
        'MarkerEdgeColor',.3*rgbMatrixForPlotting(2,:),...
        'MarkerFaceColor',rgbMatrixForPlotting(2,:),...
        'MarkerFaceAlpha', scaledContrast(ii,2));
    
    scatter(S_over_LS(ii+12),flipud(lags(ii,6)),sz, ...
        'MarkerEdgeColor',.3*rgbMatrixForPlotting(3,:),...
        'MarkerFaceColor',rgbMatrixForPlotting(3,:),...
        'MarkerFaceAlpha', scaledContrast(ii,3));
    
    scatter(S_over_LS(ii+18),flipud(lags(ii,5)),sz, ...
        'MarkerEdgeColor',.3*rgbMatrixForPlotting(4,:),...
        'MarkerFaceColor',rgbMatrixForPlotting(4,:),...
        'MarkerFaceAlpha', scaledContrast(ii,4));
    
    scatter(S_over_LS(ii+24),flipud(lags(ii,4)),sz, ...
        'MarkerEdgeColor',.3*rgbMatrixForPlotting(5,:),...
        'MarkerFaceColor',rgbMatrixForPlotting(5,:),...
        'MarkerFaceAlpha', scaledContrast(ii,5));
    
    scatter(S_over_LS(ii+30),flipud(lags(ii,3)),sz, ...
        'MarkerEdgeColor',.3*rgbMatrixForPlotting(6,:),...
        'MarkerFaceColor',rgbMatrixForPlotting(6,:),...
        'MarkerFaceAlpha', scaledContrast(ii,6));
end
axis square;
legend('0°','90°','-75°','75°','-45°','45°');


ylim([0.2 .6])



set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'FontSize'    , 16        , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'YTick'       , .2:.1:.6 , ...
    'LineWidth'   , 2         , ...
    'ActivePositionProperty', 'OuterPosition');

set(gcf, 'Color', 'white' );

hTitle  = title ('Lag Vs. S Contrast');
hXLabel = xlabel('S / (S + L) (Proportion S)');
hYLabel = ylabel('Lag (s)');

set([hTitle, hXLabel, hYLabel],'FontName', 'Helvetica');
set([hXLabel, hYLabel,],'FontSize', 18);
set( hTitle, 'FontSize', 18,'FontWeight' , 'bold');


figSavePath = '/Users/michael/labDropbox/CNST_analysis/ColorTracking/Results/';
subjID = 'Subject2';
set(tcHndl, 'Renderer', 'Painters');
figureSizeInches = [8 8];
set(tcHndl, 'PaperUnits', 'inches');
set(tcHndl, 'PaperSize',figureSizeInches);
set(tcHndl, 'PaperPosition', [0 0 figureSizeInches(1) figureSizeInches(2)]);
% Full file name
figNameTc =  fullfile(figSavePath,[subjID, '_sOverLPlusS.pdf']);
% Save it
print(tcHndl, figNameTc, '-dpdf', '-r300');




%% MAKE 3D SCATTER PLOT

figure;hold on;
scatter3(MaxContrastLMS(1:6,1),MaxContrastLMS(1:6,3),lags(:,1))

scatter3(MaxContrastLMS(7:12,1),MaxContrastLMS(7:12,3),lags(:,2))

scatter3(MaxContrastLMS(13:18,1),MaxContrastLMS(13:18,3),lags(:,6))

scatter3(MaxContrastLMS(19:24,1),MaxContrastLMS(19:24,3),lags(:,5))

scatter3(MaxContrastLMS(25:30,1),MaxContrastLMS(25:30,3),lags(:,4))

scatter3(MaxContrastLMS(31:36,1),MaxContrastLMS(31:36,3),lags(:,3))
grid on
set(gca,'LineWidth',1.5)
