%    Asano et al. give the following population SD's for the individual
%    difference parameters (their Table 5, Step 2 numbers:
%       Lens    - 18.7%
%       Macular - 36.5%
%       L Density - 9%
%       M Density - 9%
%       S Density - 7.4%
%       L Shift   - 2 nm
%       M Shift   - 1.5 nm
%       S Shift   - 1.3 nm

% Initialize
clear; close all;

% Get the stimuli settings for angles in the LS plane
% Load a CRT calibration file
cal = LoadCalFile('ViewSonicG220fb',[],getpref('ColorTracking','CalFolder'));

% Make calibration file compatible with current system
[calStructOBJ, inputArgIsACalStructOBJ] = ObjectToHandleCalOrCalStruct(cal);

% Set number of bits for display
nMonitorBits = 12;
nInputLevels = 2.^nMonitorBits;
CalibrateFitGamma(calStructOBJ, nInputLevels);
SetGammaMethod(calStructOBJ,2);

% Load the stim settings ans max contrasts for angles 80:0.05:100
% These are generated by cacheStimSettingsAsanso and then saved
% out by hand.
projectDir = tbLocateProject('ColorTracking');
cacheFileDir = fullfile(projectDir,'code','analysis','coneBootstrap');
settingsData = load(fullfile(cacheFileDir,'cacheStimSettingAsanoBoot.mat'));

% Baseline fundamentals
S = [380 5 81];
coneParams = DefaultConeParams('cie_asano');
coneParams.ageYears = 32;
coneParams.fieldSizeDegrees = 2;

% Load ss2 fundamentals
load T_cones_ss2

% Outer loop over Asano parameters
theAngles = 80:0.05:100;
nAsanoBoots = 10;
CHECK_NOMINAL = 2;
for aa = 1:nAsanoBoots

    % Draw 8 parameters with standard deviations as in comment above
    switch (CHECK_NOMINAL)
        case 0
            drawLens     = normrnd(0,18.7);
            drawMacular  = normrnd(0,36.5);
            drawLDensity = normrnd(0,9);
            drawMDensity = normrnd(0,9);
            drawSDensity = normrnd(0,7.4);
            drawLShift   = normrnd(0,2);
            drawMShift   = normrnd(0,1.5);
            drawSShift   = normrnd(0,1.3);
            while drawMacular > 100 || drawMacular < -100
                drawMacular  = normrnd(0,36.5);
            end

            % Construct cone fundamentas with those parameters
            tmpConeParams = coneParams;
            tmpConeParams.indDiffParams.lambdaMaxShift = [drawLShift drawMShift drawSShift];
            tmpConeParams.indDiffParams.dphotopigment  = [drawLDensity drawMDensity drawSDensity];
            tmpConeParams.indDiffParams.dlens = drawLens;
            tmpConeParams.indDiffParams.dmac = drawMacular;
            tmpConeParams.fieldSizeDegrees = 2;
            [~,T1] = ComputeObserverFundamentals(tmpConeParams,S_cones_ss2);
        case 1
            drawLens     = 0;
            drawMacular  = 0;
            drawLDensity = 0;
            drawMDensity = 0;
            drawSDensity = 0;
            drawLShift   = 0;
            drawMShift   = 0;
            drawSShift   = 0;

            % Construct cone fundamentas with those parameters
            tmpConeParams = coneParams;
            tmpConeParams.indDiffParams.lambdaMaxShift = [drawLShift drawMShift drawSShift];
            tmpConeParams.indDiffParams.dphotopigment  = [drawLDensity drawMDensity drawSDensity];
            tmpConeParams.indDiffParams.dlens = drawLens;
            tmpConeParams.indDiffParams.dmac = drawMacular;
            tmpConeParams.fieldSizeDegrees = 2;
            [~,T1] = ComputeObserverFundamentals(tmpConeParams,S_cones_ss2);
        case 2
            T1 = T_cones_ss2;
    end
    
    %% Standard initialization of calibration structure with modified cones
    SetSensorColorSpace(calStructOBJ,T1,S_cones_ss2);

    %% Set the background and get modified cone excitations
    backgroundPrimaries = [0.50 0.50 0.50]'; %SensorToSettings(calStructOBJ,backgroundLMS);
    backgroundLMS_hat = SettingsToSensor(calStructOBJ,PrimaryToSettings(calStructOBJ,backgroundPrimaries));

    excitationsLMS1 = SettingsToSensor(calStructOBJ,settingsData.stimSettings);
    backgroundLMS1 = repmat(backgroundLMS_hat,[1,size(excitationsLMS1,2)]);
    contrastsLMS1 = ExcitationsToContrast(excitationsLMS1,backgroundLMS1);

    %% Compute various contrasts/signals
    %
    % Luminance
    w = 2;
    backgroundLum1 = [w,1,0]*backgroundLMS1;
    luminances1 = [w,1,0]*excitationsLMS1;
    lumContrasts1 = (luminances1-backgroundLum1(1:size(excitationsLMS1,2))) ./ backgroundLum1(1:size(excitationsLMS1,2));

    % L-M contrast
    contrastsLminusM1 = contrastsLMS1(1,:)-contrastsLMS1(2,:);

    whichLumAngle = find(abs(lumContrasts1) == min(abs(lumContrasts1)));
    whichLminusMAngle = find(abs(contrastsLminusM1) == min(abs(contrastsLminusM1)));
    whichLAngle = find(abs(contrastsLMS1(1,:)) == min(abs(contrastsLMS1(1,:))));
    whichMAngle = find(abs(contrastsLMS1(2,:)) == min(abs(contrastsLMS1(2,:))));

    minLumAngle(aa)     = theAngles(whichLumAngle);
    lumContrasts_minLumAngle(aa) = lumContrasts1(whichLumAngle);
    LminusMContrasts_minLumMAngle(aa) = contrastsLminusM1(whichLumAngle);
    LContrasts_minLumAngle(aa)   = contrastsLMS1(1,whichLumAngle);
    MContrasts_minLumAngle(aa)   = contrastsLMS1(2,whichLumAngle);
    SContrasts_minLumAngle(aa)   = contrastsLMS1(3,whichLumAngle);

    minLminusMAngle(aa)     = theAngles(whichLminusMAngle);
    lumContrasts_minLminusMAngle(aa) = lumContrasts1(whichLminusMAngle);
    LminusMContrasts_minLminusMAngle(aa) = contrastsLminusM1(whichLminusMAngle);
    LContrasts_minLminusMAngle(aa)   = contrastsLMS1(1,whichLminusMAngle);
    MContrasts_minLminusMAngle(aa)   = contrastsLMS1(2,whichLminusMAngle);
    SContrasts_minLminusMAngle(aa)   = contrastsLMS1(3,whichLminusMAngle);

    minLAngle(aa)     = theAngles(whichLAngle);
    lumContrasts_minLAngle(aa) = lumContrasts1(whichLAngle);
    LContrasts_minLAngle(aa)   = contrastsLMS1(1,whichLAngle);
    MContrasts_minLAngle(aa)   = contrastsLMS1(2,whichLAngle);
    SContrasts_minLAngle(aa)   = contrastsLMS1(3,whichLAngle);

    minMAngle(aa)     = theAngles(whichMAngle);
    lumContrasts_minMAngle(aa) = lumContrasts1(whichMAngle);
    LContrasts_minMAngle(aa)   = contrastsLMS1(1,whichMAngle);
    MContrasts_minMAngle(aa)   = contrastsLMS1(2,whichMAngle);
    SContrasts_minMAngle(aa)   = contrastsLMS1(3,whichMAngle);

end

%% Plot distribution of theta's, etc.
%
% Min lum angle plot
close all;
histMax = 2000;
histBins = 50;
angleMin = 85;
angleMax = 95;
contrastMin = -5e-2;
contrastMax = 5e-2;
f1 = figure; clf;
edges = linspace(angleMin,angleMax,histBins);
h1 = histogram(minLumAngle,edges);
ylabel('Count')
xlabel('Angle in LS Plane')
title('Minimum Luminance Contrast Angle')
set(gcf,'Color','w');
xlim([angleMin angleMax]);
ylim([0 histMax]);
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1, ...
    'FontSize'    , 12);
axis square

f2 = figure; clf;
edges = linspace(contrastMin,contrastMax,histBins);
h1 = histogram(100*lumContrasts_minLumAngle,edges );
ylabel('Count')
xlabel('Luminance Contrast (%)')
title('Luminance Contrast at Minimum Luminance Angle')
set(gcf,'Color','w');
xlim([contrastMin contrastMax]);
ylim([0 histMax]);
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1, ...
    'FontSize'    , 12);
axis square

%% Min LminusM angle plot
f3 = figure; clf;
edges = linspace(angleMin,angleMax,histBins);
h1 = histogram(minLminusMAngle,edges);
ylabel('Count')
xlabel('Angle in LS Plane')
title('Minimum L-M Contrast Angle')
set(gcf,'Color','w');
xlim([angleMin angleMax]);
ylim([0 histMax]);
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1, ...
    'FontSize'    , 12);
axis square

f4 = figure; clf;
edges = linspace(contrastMin,contrastMax,histBins);
h1 = histogram(100*LminusMContrasts_minLminusMAngle,edges);
ylabel('Count')
xlabel('L-M Contrast (%)')
title('L-M Contrast at Minimum L-M Angle')
set(gcf,'Color','w');
xlim([contrastMin contrastMax]);
ylim([0 histMax]);
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1, ...
    'FontSize'    , 12);
axis square

%% Save figures
%{
    figureRootPath = '/Users/dhb/Desktop';
    saveas(f1,fullfile(figureRootPath,'FigureS5a.pdf'),'pdf');
    saveas(f2,fullfile(figureRootPath,'FigureS5b.pdf'),'pdf');
    saveas(f3,fullfile(figureRootPath,'FigureS5c.pdf'),'pdf');
    saveas(f4,fullfile(figureRootPath,'FigureS5d.pdf'),'pdf');
%}

